/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/WordFormModal`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateTheme`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EditTheme`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FlashcardGame`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Statistics`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ThemeList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WordList`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/WordFormModal`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CreateTheme`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EditTheme`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/FlashcardGame`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Statistics`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ThemeList`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WordList`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/WordFormModal${`?${string}` | `#${string}` | ''}` | `/screens/CreateTheme${`?${string}` | `#${string}` | ''}` | `/screens/Dashboard${`?${string}` | `#${string}` | ''}` | `/screens/EditTheme${`?${string}` | `#${string}` | ''}` | `/screens/FlashcardGame${`?${string}` | `#${string}` | ''}` | `/screens/Statistics${`?${string}` | `#${string}` | ''}` | `/screens/ThemeList${`?${string}` | `#${string}` | ''}` | `/screens/WordList${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/WordFormModal`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateTheme`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EditTheme`; params?: Router.UnknownInputParams; } | { pathname: `/screens/FlashcardGame`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Statistics`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ThemeList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WordList`; params?: Router.UnknownInputParams; };
    }
  }
}
